import { createHash, randomUUID } from "node:crypto";
import { mkdir, readFile } from "node:fs/promises";
import { join } from "node:path";

import { PGlite } from "@electric-sql/pglite";

import type { AutomationSettings } from "../../editorial/src/automation.ts";
import {
  canonicalJson,
  type Approval,
  type ApprovalV3,
  type ArticleRevision,
  type HighRiskApproval
} from "../../editorial/src/revision.ts";
import {
  assertValidApprovalRevocation,
  BackendStoreError,
  type ApprovalRevocation,
  type BackendChange,
  type BackendJob,
  type DashboardReadOptions,
  type DashboardSyncResult,
  type RevisionListReadOptions,
  type RevisionListSnapshot,
  type RevisionLineageIndexEntry,
  type RevisionEvidenceReference,
  type BackendRepository,
  type BackendRepositoryTransaction,
  type OutboxEffect,
  type PublicationIntentBinding,
  type SyncResult
} from "./backend-repository.ts";
import { isEncryptedEnvelopeV2, JsonProtector } from "./encrypted-json.ts";

interface QueryResult<Row> {
  rows: Row[];
}

interface PGliteQueryPort {
  query<Row>(
    sql: string,
    parameters?: readonly unknown[]
  ): Promise<QueryResult<Row>>;
  exec(sql: string): Promise<unknown>;
}

interface PGliteDatabasePort extends PGliteQueryPort {
  transaction<T>(
    operation: (transaction: PGliteQueryPort) => Promise<T>
  ): Promise<T>;
  close(): Promise<void>;
}

interface JsonRow {
  key?: string;
  value: unknown;
}

interface IdempotencyRow {
  request_fingerprint: string;
  response_json: unknown;
}

interface ChangeRow {
  cursor: string | number;
  kind: BackendChange["kind"];
  entity_id: string;
}

const LOCAL_SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS blogbot_automation (
  singleton_id smallint PRIMARY KEY CHECK (singleton_id = 1),
  value jsonb NOT NULL
);

INSERT INTO blogbot_automation (singleton_id, value)
VALUES (
  1,
  '{
    "mode":"INGEST_ONLY",
    "onboardingComplete":false,
    "ingestionPaused":false,
    "publishingPaused":true,
    "timezone":"Europe/Istanbul",
    "scanIntervalMinutes":30
  }'::jsonb
)
ON CONFLICT (singleton_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS blogbot_revisions (
  id text PRIMARY KEY,
  value jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS blogbot_approvals (
  revision_id text PRIMARY KEY,
  value jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS blogbot_outbox (
  id text PRIMARY KEY,
  idempotency_key text NOT NULL UNIQUE,
  value jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS blogbot_jobs (
  id text PRIMARY KEY,
  value jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS blogbot_changes (
  cursor bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  kind text NOT NULL,
  entity_id text NOT NULL
);

CREATE TABLE IF NOT EXISTS blogbot_idempotency (
  idempotency_key text PRIMARY KEY,
  request_fingerprint text NOT NULL,
  response_json jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS blogbot_encryption_migrations (
  scope text PRIMARY KEY,
  version integer NOT NULL
);
`;

const LOCAL_MIGRATIONS = [
  {
    version: 1,
    name: "local-engine-core",
    sql: LOCAL_SCHEMA_SQL
  },
  {
    version: 2,
    name: "high-risk-approvals",
    sql: `
CREATE TABLE IF NOT EXISTS blogbot_high_risk_approvals (
  revision_id text PRIMARY KEY,
  value jsonb NOT NULL
);
`
  },
  {
    version: 3,
    name: "codex-jobs",
    sql: `
CREATE TABLE IF NOT EXISTS blogbot_codex_jobs (
  id text PRIMARY KEY,
  idempotency_key text NOT NULL UNIQUE,
  state text NOT NULL,
  version integer NOT NULL CHECK (version > 0),
  value jsonb NOT NULL
);
`
  },
  {
    version: 4,
    name: "local-state",
    sql: `
CREATE TABLE IF NOT EXISTS blogbot_local_state (
  key text PRIMARY KEY,
  value jsonb NOT NULL
);
`
  },
  {
    version: 5,
    name: "revision-list-index",
    sql: `
CREATE TABLE IF NOT EXISTS blogbot_revision_list_index (
  revision_id text PRIMARY KEY,
  scheduled_at_unix_ms bigint NOT NULL,
  supersedes_revision_id text,
  value jsonb NOT NULL
);
CREATE INDEX IF NOT EXISTS blogbot_revision_list_due_idx
  ON blogbot_revision_list_index (scheduled_at_unix_ms, revision_id);
CREATE INDEX IF NOT EXISTS blogbot_revision_list_parent_idx
  ON blogbot_revision_list_index (supersedes_revision_id);
`
  },
  {
    version: 6,
    name: "operational-row-order-and-version",
    sql: `
ALTER TABLE blogbot_outbox
  ADD COLUMN IF NOT EXISTS seq bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE blogbot_outbox
  ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS blogbot_outbox_seq_idx
  ON blogbot_outbox (seq DESC);

ALTER TABLE blogbot_jobs
  ADD COLUMN IF NOT EXISTS seq bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE blogbot_jobs
  ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS blogbot_jobs_seq_idx
  ON blogbot_jobs (seq DESC);
`
  },
  {
    version: 7,
    name: "revision-list-state",
    sql: `
ALTER TABLE blogbot_revision_list_index
  ADD COLUMN IF NOT EXISTS revision_state text;
CREATE INDEX IF NOT EXISTS blogbot_revision_list_state_due_idx
  ON blogbot_revision_list_index (revision_state, scheduled_at_unix_ms, revision_id);
`
  },
  {
    version: 8,
    name: "encryption-migration-progress",
    sql: `
CREATE TABLE IF NOT EXISTS blogbot_encryption_migration_progress (
  scope text NOT NULL,
  table_name text NOT NULL,
  last_key text NOT NULL,
  PRIMARY KEY (scope, table_name)
);
`
  },
  {
    version: 9,
    name: "approval-revocations",
    sql: `
CREATE TABLE IF NOT EXISTS blogbot_approval_revocations (
  revision_id text PRIMARY KEY,
  value jsonb NOT NULL
);
`
  }
] as const;

/**
 * States a revision can never leave for publication. Everything else stays in
 * the due list so the editorial eligibility check remains the only authority.
 */
const SCHEDULER_TERMINAL_REVISION_STATES = ["PUBLISHING", "PUBLISHED"] as const;

/**
 * Row-rewriting migrations commit one page at a time. A workspace with hundreds
 * of revisions carrying generated media cannot hold the whole decrypted
 * database in one transaction, and a crash must not restart from row zero.
 */
const MIGRATION_PAGE_SIZE = 200;

const MIGRATION_LEDGER_SQL = `
CREATE TABLE IF NOT EXISTS blogbot_schema_migrations (
  version integer PRIMARY KEY,
  name text NOT NULL,
  sha256 text NOT NULL,
  applied_at timestamptz NOT NULL DEFAULT now()
);
`;

class PGliteTransactionRepository implements BackendRepositoryTransaction {
  constructor(
    protected readonly client: PGliteQueryPort,
    protected readonly protector: JsonProtector
  ) {}

  async getVersion(): Promise<number> {
    const result = await this.client.query<{ cursor: string | number }>(
      "SELECT COALESCE(MAX(cursor), 0) AS cursor FROM blogbot_changes"
    );
    return Number(result.rows[0]?.cursor ?? 0);
  }

  async setAutomation(settings: AutomationSettings): Promise<void> {
    await this.client.query(
      "UPDATE blogbot_automation SET value = $1::jsonb WHERE singleton_id = 1",
      [JSON.stringify(this.protector.seal(settings, backendContext("blogbot_automation", "1")))]
    );
    await this.recordChange("AUTOMATION_UPDATED", "automation");
  }

  async getAutomation(): Promise<AutomationSettings> {
    const result = await this.client.query<JsonRow>(
      "SELECT value FROM blogbot_automation WHERE singleton_id = 1"
    );
    return this.protector.open<AutomationSettings>(
      result.rows[0]?.value,
      backendContext("blogbot_automation", "1")
    );
  }

  async insertRevision(revision: ArticleRevision): Promise<ArticleRevision> {
    const existing = await this.client.query<JsonRow>(
      "SELECT value FROM blogbot_revisions WHERE id = $1",
      [revision.id]
    );
    if (existing.rows[0]) {
      const saved = this.protector.open<ArticleRevision>(
        existing.rows[0].value,
        backendContext("blogbot_revisions", revision.id)
      );
      if (canonicalJson(saved) !== canonicalJson(revision)) {
        throw new BackendStoreError(
          "IMMUTABLE_REVISION",
          `Revision ${revision.id} already exists with different content`
        );
      }
      return structuredClone(saved);
    }
    await this.client.query(
      "INSERT INTO blogbot_revisions (id, value) VALUES ($1, $2::jsonb)",
      [
        revision.id,
        JSON.stringify(
          this.protector.seal(
            revision,
            backendContext("blogbot_revisions", revision.id)
          )
        )
      ]
    );
    await writeRevisionListIndex(this.client, this.protector, revision);
    await this.recordChange("REVISION_SUBMITTED", revision.id);
    return structuredClone(revision);
  }

  async getRevision(revisionId: string): Promise<ArticleRevision> {
    const result = await this.client.query<JsonRow>(
      "SELECT value FROM blogbot_revisions WHERE id = $1",
      [revisionId]
    );
    if (!result.rows[0]) {
      throw new BackendStoreError(
        "REVISION_NOT_FOUND",
        `Revision ${revisionId} was not found`
      );
    }
    return this.protector.open<ArticleRevision>(
      result.rows[0].value,
      backendContext("blogbot_revisions", revisionId)
    );
  }

  async getApproval(revisionId: string): Promise<Approval | ApprovalV3 | null> {
    const result = await this.client.query<JsonRow>(
      "SELECT value FROM blogbot_approvals WHERE revision_id = $1",
      [revisionId]
    );
    if (!result.rows[0]) return null;
    return this.protector.open<Approval | ApprovalV3>(
      result.rows[0].value,
      backendContext("blogbot_approvals", revisionId)
    );
  }

  async getApprovalRevocation(revisionId: string): Promise<ApprovalRevocation | null> {
    const result = await this.client.query<JsonRow>(
      "SELECT value FROM blogbot_approval_revocations WHERE revision_id = $1",
      [revisionId]
    );
    return result.rows[0]
      ? this.protector.open<ApprovalRevocation>(
          result.rows[0].value,
          backendContext("blogbot_approval_revocations", revisionId)
        )
      : null;
  }

  async saveApproval<T extends Approval | ApprovalV3>(approval: T): Promise<T> {
    const existing = await this.client.query<JsonRow>(
      "SELECT value FROM blogbot_approvals WHERE revision_id = $1",
      [approval.revisionId]
    );
    if (existing.rows[0]) {
      const saved = this.protector.open<T>(
        existing.rows[0].value,
        backendContext("blogbot_approvals", approval.revisionId)
      );
      if (canonicalJson(saved) === canonicalJson(approval)) {
        return structuredClone(saved);
      }
      throw new BackendStoreError(
        "REVISION_ALREADY_APPROVED",
        `Revision ${approval.revisionId} already has an immutable approval`
      );
    }
    await this.client.query(
      "INSERT INTO blogbot_approvals (revision_id, value) VALUES ($1, $2::jsonb)",
      [
        approval.revisionId,
        JSON.stringify(
          this.protector.seal(
            approval,
            backendContext("blogbot_approvals", approval.revisionId)
          )
        )
      ]
    );
    await this.recordChange("REVISION_APPROVED", approval.revisionId);
    return structuredClone(approval);
  }

  async revokeApproval(revocation: ApprovalRevocation): Promise<ApprovalRevocation> {
    assertValidApprovalRevocation(revocation);
    const approval = await this.getApproval(revocation.revisionId);
    if (!approval) {
      throw new BackendStoreError(
        "APPROVAL_NOT_FOUND",
        `Revision ${revocation.revisionId} does not have an editorial approval`
      );
    }
    if (approval.revisionHash !== revocation.revisionHash) {
      throw new BackendStoreError(
        "APPROVAL_HASH_MISMATCH",
        `Revision ${revocation.revisionId} approval hash does not match the revocation`
      );
    }
    const existing = await this.getApprovalRevocation(revocation.revisionId);
    if (existing) {
      if (canonicalJson(existing) === canonicalJson(revocation)) {
        return structuredClone(existing);
      }
      throw new BackendStoreError(
        "APPROVAL_ALREADY_REVOKED",
        `Revision ${revocation.revisionId} already has an immutable revocation`
      );
    }
    await this.client.query(
      "INSERT INTO blogbot_approval_revocations (revision_id, value) VALUES ($1, $2::jsonb)",
      [
        revocation.revisionId,
        JSON.stringify(
          this.protector.seal(
            revocation,
            backendContext("blogbot_approval_revocations", revocation.revisionId)
          )
        )
      ]
    );
    await this.recordChange("APPROVAL_REVOKED", revocation.revisionId);
    return structuredClone(revocation);
  }

  async saveHighRiskApproval(
    approval: HighRiskApproval
  ): Promise<HighRiskApproval> {
    const existing = await this.client.query<JsonRow>(
      "SELECT value FROM blogbot_high_risk_approvals WHERE revision_id = $1",
      [approval.revisionId]
    );
    if (existing.rows[0]) {
      const saved = this.protector.open<HighRiskApproval>(
        existing.rows[0].value,
        backendContext("blogbot_high_risk_approvals", approval.revisionId)
      );
      if (canonicalJson(saved) === canonicalJson(approval)) {
        return structuredClone(saved);
      }
      throw new BackendStoreError(
        "REVISION_ALREADY_APPROVED",
        `Revision ${approval.revisionId} already has an immutable high-risk approval`
      );
    }
    await this.client.query(
      `INSERT INTO blogbot_high_risk_approvals (revision_id, value)
       VALUES ($1, $2::jsonb)`,
      [
        approval.revisionId,
        JSON.stringify(
          this.protector.seal(
            approval,
            backendContext("blogbot_high_risk_approvals", approval.revisionId)
          )
        )
      ]
    );
    await this.recordChange(
      "REVISION_APPROVED",
      `${approval.revisionId}:HIGH_RISK`
    );
    return structuredClone(approval);
  }

  async enqueuePublication(
    revisionId: string,
    revisionHash: string,
    binding: PublicationIntentBinding
  ): Promise<OutboxEffect> {
    const idempotencyKey = `publish:${revisionId}:${revisionHash}:${binding.previewHash}`;
    const effect: OutboxEffect = {
      id: randomUUID(),
      type: "PUBLISH_REVISION",
      aggregateId: revisionId,
      revisionHash,
      ...structuredClone(binding),
      idempotencyKey,
      state: "PENDING",
      attempts: 0
    };
    const inserted = await this.client.query<{ id: string }>(
      `INSERT INTO blogbot_outbox (id, idempotency_key, value)
       VALUES ($1, $2, $3::jsonb)
       ON CONFLICT (idempotency_key) DO NOTHING
       RETURNING id`,
      [
        effect.id,
        effect.idempotencyKey,
        JSON.stringify(
          this.protector.seal(
            effect,
            backendContext("blogbot_outbox", effect.id)
          )
        )
      ]
    );
    if (inserted.rows[0]) {
      // Creation and later state transitions must be equally visible to the
      // incremental desktop sync feed; otherwise a freshly queued publication
      // can be invisible until an unrelated mutation happens.
      await this.recordChange("EFFECT_UPDATED", effect.id);
      return structuredClone(effect);
    }

    const existing = await this.client.query<JsonRow>(
      "SELECT id AS key, value FROM blogbot_outbox WHERE idempotency_key = $1",
      [idempotencyKey]
    );
    const row = existing.rows[0];
    if (!row?.key) throw new Error("LOCAL_DATA_IDENTITY_MISSING");
    return this.protector.open<OutboxEffect>(
      row.value,
      backendContext("blogbot_outbox", row.key)
    );
  }
  async listOutbox(): Promise<OutboxEffect[]> {
    const result = await this.client.query<JsonRow>(
      "SELECT id AS key, value FROM blogbot_outbox ORDER BY id"
    );
    return result.rows.map((row) => {
      if (!row.key) throw new Error("LOCAL_DATA_IDENTITY_MISSING");
      return this.protector.open<OutboxEffect>(
        row.value,
        backendContext("blogbot_outbox", row.key)
      );
    });
  }

  async getOutboxEffect(effectId: string): Promise<{ effect: OutboxEffect; version: number }> {
    const result = await this.client.query<JsonRow & { version: number }>(
      "SELECT id AS key, value, version FROM blogbot_outbox WHERE id = $1",
      [effectId]
    );
    const row = result.rows[0];
    if (!row?.key) throw new Error(`Outbox effect ${effectId} was not found`);
    return {
      effect: this.protector.open<OutboxEffect>(
        row.value,
        backendContext("blogbot_outbox", row.key)
      ),
      version: Number(row.version)
    };
  }

  async updateOutbox(
    effect: OutboxEffect,
    expectedVersion: number
  ): Promise<OutboxEffect> {
    const sealed = JSON.stringify(
      this.protector.seal(effect, backendContext("blogbot_outbox", effect.id))
    );
    const result = await this.client.query<{ id: string }>(
        `UPDATE blogbot_outbox
            SET value = $2::jsonb, version = version + 1
          WHERE id = $1 AND version = $3
        RETURNING id`,
        [effect.id, sealed, expectedVersion]
      );
    if (!result.rows[0]) {
      // The row exists but moved on, or it is gone; either way this whole-row
      // overwrite would have destroyed another lane's write.
      throw new BackendStoreError(
        "WRITE_VERSION_CONFLICT",
        `Outbox effect ${effect.id} is no longer at version ${expectedVersion}`
      );
    }
    await this.recordChange("EFFECT_UPDATED", effect.id);
    return structuredClone(effect);
  }

  async getOutboxVersion(effectId: string): Promise<number> {
    const result = await this.client.query<{ version: number }>(
      "SELECT version FROM blogbot_outbox WHERE id = $1",
      [effectId]
    );
    const row = result.rows[0];
    if (!row) throw new Error(`Outbox effect ${effectId} was not found`);
    return Number(row.version);
  }

  async createJob(job: BackendJob): Promise<BackendJob> {
    try {
      await this.client.query(
        "INSERT INTO blogbot_jobs (id, value) VALUES ($1, $2::jsonb)",
        [
          job.id,
          JSON.stringify(
            this.protector.seal(job, backendContext("blogbot_jobs", job.id))
          )
        ]
      );
    } catch (error) {
      if (isUniqueViolation(error)) {
        throw new Error(`Job ${job.id} already exists`, { cause: error });
      }
      throw error;
    }
    await this.recordChange("JOB_UPDATED", job.id);
    return structuredClone(job);
  }

  async getJob(jobId: string): Promise<BackendJob> {
    return (await this.getJobRecord(jobId)).job;
  }

  async getJobRecord(jobId: string): Promise<{ job: BackendJob; version: number }> {
    const result = await this.client.query<JsonRow & { version: number }>(
      "SELECT value, version FROM blogbot_jobs WHERE id = $1",
      [jobId]
    );
    if (!result.rows[0]) {
      throw new Error(`Job ${jobId} was not found`);
    }
    return {
      job: this.protector.open<BackendJob>(
        result.rows[0].value,
        backendContext("blogbot_jobs", jobId)
      ),
      version: Number(result.rows[0].version)
    };
  }

  async saveJob(job: BackendJob, expectedVersion: number): Promise<BackendJob> {
    const sealed = JSON.stringify(
      this.protector.seal(job, backendContext("blogbot_jobs", job.id))
    );
    const result = await this.client.query<{ id: string }>(
        `UPDATE blogbot_jobs
            SET value = $2::jsonb, version = version + 1
          WHERE id = $1 AND version = $3
        RETURNING id`,
        [job.id, sealed, expectedVersion]
      );
    if (!result.rows[0]) {
      // A job write replaces state, attempts and metadata together, so losing
      // this race silently would drop either the completion or the retry.
      throw new BackendStoreError(
        "WRITE_VERSION_CONFLICT",
        `Job ${job.id} is no longer at version ${expectedVersion}`
      );
    }
    await this.recordChange("JOB_UPDATED", job.id);
    return structuredClone(job);
  }

  async getJobVersion(jobId: string): Promise<number> {
    const result = await this.client.query<{ version: number }>(
      "SELECT version FROM blogbot_jobs WHERE id = $1",
      [jobId]
    );
    const row = result.rows[0];
    if (!row) throw new Error(`Job ${jobId} was not found`);
    return Number(row.version);
  }

  async listJobs(): Promise<BackendJob[]> {
    const result = await this.client.query<JsonRow>(
      "SELECT id AS key, value FROM blogbot_jobs ORDER BY id"
    );
    return result.rows.map((row) => {
      if (!row.key) throw new Error("LOCAL_DATA_IDENTITY_MISSING");
      return this.protector.open<BackendJob>(
        row.value,
        backendContext("blogbot_jobs", row.key)
      );
    });
  }

  async getLocalState(key: string): Promise<unknown | undefined> {
    const result = await this.client.query<JsonRow>(
      "SELECT value FROM blogbot_local_state WHERE key = $1",
      [key]
    );
    const row = result.rows[0];
    return row ? this.protector.open(row.value, backendContext("blogbot_local_state", key)) : undefined;
  }

  async setLocalState(key: string, value: unknown): Promise<void> {
    await this.client.query(
      `INSERT INTO blogbot_local_state (key, value) VALUES ($1, $2::jsonb)
       ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value`,
      [key, JSON.stringify(this.protector.seal(value, backendContext("blogbot_local_state", key)))]
    );
    await this.recordChange("LOCAL_STATE_UPDATED", key);
  }

  async getHighRiskApproval(revisionId: string): Promise<HighRiskApproval | null> {
    const result = await this.client.query<JsonRow>(
      "SELECT value FROM blogbot_high_risk_approvals WHERE revision_id = $1",
      [revisionId]
    );
    return result.rows[0]
      ? this.protector.open<HighRiskApproval>(
        result.rows[0].value,
        backendContext("blogbot_high_risk_approvals", revisionId)
      )
      : null;
  }

  async setMaintenanceState(key: string, value: unknown): Promise<void> {
    if (!key.startsWith("maintenance.")) {
      throw new BackendStoreError("INVALID_MAINTENANCE_KEY", "Maintenance state keys must start with maintenance.");
    }
    await this.client.query(
      `INSERT INTO blogbot_local_state (key, value) VALUES ($1, $2::jsonb)
       ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value`,
      [key, JSON.stringify(this.protector.seal(value, backendContext("blogbot_local_state", key)))]
    );
  }

  protected async recordChange(
    kind: BackendChange["kind"],
    entityId: string
  ): Promise<void> {
    await this.client.query(
      "INSERT INTO blogbot_changes (kind, entity_id) VALUES ($1, $2)",
      [kind, entityId]
    );
  }
}

export class PGliteBackendRepository
  extends PGliteTransactionRepository
  implements BackendRepository
{
  readonly persistence = "pglite" as const;

  private constructor(
    private readonly database: PGliteDatabasePort,
    protector: JsonProtector
  ) {
    super(database, protector);
  }

  static async open(dataDir: string): Promise<PGliteBackendRepository> {
    await mkdir(dataDir, { recursive: true });
    const assetDirectory = process.env.BLOGBOT_PGLITE_ASSETS?.trim();
    const database = assetDirectory
      ? new PGlite({
          dataDir,
          pgliteWasmModule: await WebAssembly.compile(
            await readFile(join(assetDirectory, "pglite.wasm"))
          ),
          initdbWasmModule: await WebAssembly.compile(
            await readFile(join(assetDirectory, "initdb.wasm"))
          ),
          fsBundle: new Blob([
            await readFile(join(assetDirectory, "pglite.data"))
          ])
        })
      : new PGlite(dataDir);
    try {
      await database.waitReady;
      await applyLocalMigrations(database);
      const protector = JsonProtector.fromEnvironment();
      await encryptLegacyBackendRows(database, protector);
      await backfillRevisionListIndex(database, protector);
      return new PGliteBackendRepository(database, protector);
    } catch (error) {
      // Until open succeeds there is no caller that can own this database.
      // Complete shutdown before allowing a retry to open the same directory.
      const failures: unknown[] = [error];
      try {
        await database.close();
      } catch (cleanupError) {
        failures.push(cleanupError);
      }
      if (failures.length > 1) {
        throw new AggregateError(
          failures,
          "LOCAL_DATABASE_INITIALIZATION_CLEANUP_FAILED",
          { cause: error }
        );
      }
      throw error;
    }
  }

  /** Explicit, potentially expensive full encrypted-row integrity check. */
  async verifyEncryptionIntegrity(): Promise<void> {
    await encryptLegacyBackendRows(this.database, this.protector, true);
  }

  async close(): Promise<void> {
    await this.database.close();
  }

  getDatabase(): PGlite {
    return this.database as PGlite;
  }

  async sync(afterCursor: number): Promise<SyncResult> {
    return this.database.transaction((transaction) =>
      readSyncSnapshot(transaction, this.protector, afterCursor)
    );
  }

  async syncDashboard(afterCursor: number, options: DashboardReadOptions = {}): Promise<DashboardSyncResult> {
    return this.database.transaction((transaction) =>
      readDashboardSync(transaction, this.protector, afterCursor, options)
    );
  }

  async listRevisionSnapshot(): Promise<RevisionListSnapshot> {
    return this.database.transaction((transaction) => readRevisionListSnapshot(transaction, this.protector));
  }

  async listRevisionSummarySnapshot(options: RevisionListReadOptions = {}): Promise<RevisionListSnapshot> {
    return this.database.transaction((transaction) => readRevisionSummarySnapshot(transaction, this.protector, options));
  }

  async listDueRevisionIds(nowUnixMs: number, limit = 100, offset = 0): Promise<string[]> {
    // A revision whose schedule has passed matches forever, so without a state
    // filter every scheduler tick re-read and re-decrypted every revision the
    // workspace has ever published. Terminal states are excluded rather than
    // publishable ones allowlisted: an unrecognised state must still reach the
    // eligibility check, never silently stop being scheduled.
    const result = await this.database.query<{ revision_id: string }>(
      `SELECT revision_id FROM blogbot_revision_list_index
        WHERE scheduled_at_unix_ms <= $1
          AND (revision_state IS NULL OR revision_state <> ALL($4::text[]))
        ORDER BY scheduled_at_unix_ms, revision_id
        LIMIT $2 OFFSET $3`,
      [
        nowUnixMs,
        Math.min(Math.max(1, limit), 200),
        Math.max(0, offset),
        SCHEDULER_TERMINAL_REVISION_STATES
      ]
    );
    return result.rows.map((row) => row.revision_id);
  }

  async listRevisionLineage(): Promise<RevisionLineageIndexEntry[]> {
    const result = await this.database.query<{
      revision_id: string;
      supersedes_revision_id: string | null;
    }>("SELECT revision_id, supersedes_revision_id FROM blogbot_revision_list_index");
    return result.rows.map((row) => ({
      id: row.revision_id,
      ...(row.supersedes_revision_id ? { supersedesRevisionId: row.supersedes_revision_id } : {})
    }));
  }

  async listRevisionEvidenceReferences(): Promise<RevisionEvidenceReference[]> {
    const result = await this.database.query<{ revision_id: string; value: unknown }>(
      "SELECT revision_id, value FROM blogbot_revision_list_index"
    );
    return result.rows.map((row) => {
      const summary = this.protector.open<ArticleRevision>(
        row.value,
        backendContext("blogbot_revision_list_index", row.revision_id)
      );
      return {
        sources: summary.sources.map(({ id, evidenceVersionId }) => ({
          id,
          ...(evidenceVersionId ? { evidenceVersionId } : {})
        }))
      };
    });
  }

  async runIdempotent<T>(
    idempotencyKey: string,
    requestFingerprint: string,
    operation: (
      transaction: BackendRepositoryTransaction
    ) => Promise<T> | T
  ): Promise<T> {
    return this.database.transaction(async (client) => {
      const fingerprintHash = createHash("sha256")
        .update(requestFingerprint)
        .digest("hex");
      const existing = await client.query<IdempotencyRow>(
        `SELECT request_fingerprint, response_json
           FROM blogbot_idempotency
          WHERE idempotency_key = $1`,
        [idempotencyKey]
      );
      const row = existing.rows[0];
      if (row) {
        if (row.request_fingerprint !== fingerprintHash) {
          throw new BackendStoreError(
            "IDEMPOTENCY_KEY_REUSED",
            "Idempotency key was already used with a different request"
          );
        }
        return this.protector.open<T>(
          row.response_json,
          backendContext("blogbot_idempotency", idempotencyKey, "response_json")
        );
      }

      const result = await operation(
        new PGliteTransactionRepository(client, this.protector)
      );
      await client.query(
        `INSERT INTO blogbot_idempotency (
           idempotency_key,
           request_fingerprint,
           response_json
         ) VALUES ($1, $2, $3::jsonb)`,
        [
          idempotencyKey,
          fingerprintHash,
          JSON.stringify(
            this.protector.seal(
              result,
              backendContext(
                "blogbot_idempotency",
                idempotencyKey,
                "response_json"
              )
            )
          )
        ]
      );
      return structuredClone(result);
    });
  }
}

/**
 * A legacy row is unauthenticated, so the reseal path has to decide on shape
 * alone whether the value really is the record that belongs to this row. Each
 * check re-derives the identity binding the v2 AAD would have provided, which is
 * the strongest statement available before a key was ever bound to a row.
 */
const LEGACY_BACKEND_TABLES = [
  {
    name: "blogbot_revisions",
    key: "id",
    isExpected: (value: unknown, key: string) =>
      isRecordWithIdentity(value, "id", key) &&
      typeof value.state === "string" &&
      isPlainRecord(value.tr) &&
      Array.isArray(value.sources) &&
      Array.isArray(value.claims)
  },
  {
    name: "blogbot_approvals",
    key: "revision_id",
    isExpected: (value: unknown, key: string) =>
      isRecordWithIdentity(value, "revisionId", key) &&
      typeof value.revisionHash === "string"
  },
  {
    name: "blogbot_high_risk_approvals",
    key: "revision_id",
    isExpected: (value: unknown, key: string) =>
      isRecordWithIdentity(value, "revisionId", key) &&
      typeof value.revisionHash === "string"
  },
  {
    name: "blogbot_approval_revocations",
    key: "revision_id",
    isExpected: (value: unknown, key: string) =>
      isRecordWithIdentity(value, "revisionId", key) &&
      typeof value.revisionHash === "string" &&
      typeof value.revokedAt === "string"
  },
  {
    name: "blogbot_revision_list_index",
    key: "revision_id",
    isExpected: (value: unknown, key: string) =>
      isRecordWithIdentity(value, "id", key) && typeof value.state === "string"
  },
  {
    name: "blogbot_outbox",
    key: "id",
    isExpected: (value: unknown, key: string) =>
      isRecordWithIdentity(value, "id", key) &&
      typeof value.idempotencyKey === "string" &&
      typeof value.revisionHash === "string"
  },
  {
    name: "blogbot_jobs",
    key: "id",
    isExpected: (value: unknown, key: string) =>
      isRecordWithIdentity(value, "id", key) &&
      typeof value.kind === "string" &&
      typeof value.state === "string"
  },
  {
    name: "blogbot_codex_jobs",
    key: "id",
    isExpected: (value: unknown, key: string) =>
      isRecordWithIdentity(value, "id", key)
  }
] as const;

/**
 * Rewrites pre-v2 rows into identity-bound envelopes, or re-opens every sealed
 * row when an operator asks for an explicit integrity pass.
 *
 * Every row-rewriting loop is paged with a keyset cursor and each page commits
 * on its own, with the last completed key recorded next to the scope. Reading
 * whole tables into one transaction meant a workspace whose revisions carry
 * generated media could never finish upgrading: the sidecar exhausted its heap,
 * the transaction rolled back, the sentinel was never written, and the next
 * launch restarted from row zero and died at the same place.
 */
async function encryptLegacyBackendRows(
  database: PGliteDatabasePort,
  protector: JsonProtector,
  verifyCompleted = false
): Promise<void> {
  const migration = await database.query<{ version: number }>(
    "SELECT version FROM blogbot_encryption_migrations WHERE scope = 'backend'"
  );
  const appliedVersion = migration.rows[0]?.version;
  if (appliedVersion !== undefined && appliedVersion !== 2) {
    throw new Error(
      `LOCAL_ENCRYPTION_MIGRATION_UNSUPPORTED: backend version ${appliedVersion}`
    );
  }
  // A completed migration is the startup sentinel. Re-opening every
  // encrypted row on every launch turns normal startup into an O(n)
  // corruption scan; operators can request that scan explicitly instead.
  if (appliedVersion === 2 && !verifyCompleted) return;
  const reseal = appliedVersion === undefined;

  await database.transaction(async (transaction) => {
    const automation = await transaction.query<JsonRow>(
      "SELECT value FROM blogbot_automation WHERE singleton_id = 1"
    );
    const automationValue = automation.rows[0]?.value;
    if (automationValue === undefined) return;
    // The singleton row has no page marker, so a resumed reseal meets it again.
    // Verifying an already-sealed row is strictly stronger than resealing it,
    // and it keeps a restarted migration from failing on its own earlier work.
    if (!reseal || isEncryptedEnvelopeV2(automationValue)) {
      protector.open<AutomationSettings>(
        automationValue,
        backendContext("blogbot_automation", "1")
      );
      return;
    }
    const plaintext = protector.openLegacy<AutomationSettings>(
      automationValue,
      (candidate) =>
        isPlainRecord(candidate) &&
        typeof candidate.mode === "string" &&
        typeof candidate.timezone === "string"
    );
    await transaction.query(
      "UPDATE blogbot_automation SET value = $1::jsonb WHERE singleton_id = 1",
      [
        JSON.stringify(
          protector.seal(plaintext, backendContext("blogbot_automation", "1"))
        )
      ]
    );
  });

  for (const table of LEGACY_BACKEND_TABLES) {
    let cursor = reseal
      ? await readMigrationProgress(database, "backend", table.name)
      : "";
    for (;;) {
      const rows = await database.query<{ key: string; value: unknown }>(
        `SELECT ${table.key} AS key, value FROM ${table.name}
          WHERE ${table.key} > $1
          ORDER BY ${table.key}
          LIMIT $2`,
        [cursor, MIGRATION_PAGE_SIZE]
      );
      if (rows.rows.length === 0) break;
      const lastKey = rows.rows[rows.rows.length - 1]!.key;
      await database.transaction(async (transaction) => {
        for (const row of rows.rows) {
          if (!reseal || isEncryptedEnvelopeV2(row.value)) {
            protector.open(row.value, backendContext(table.name, row.key));
            continue;
          }
          const plaintext = protector.openLegacy(
            row.value,
            (candidate) => table.isExpected(candidate, row.key)
          );
          await transaction.query(
            `UPDATE ${table.name} SET value = $2::jsonb WHERE ${table.key} = $1`,
            [
              row.key,
              JSON.stringify(
                protector.seal(plaintext, backendContext(table.name, row.key))
              )
            ]
          );
        }
        if (reseal) {
          await writeMigrationProgress(transaction, "backend", table.name, lastKey);
        }
      });
      cursor = lastKey;
      if (reseal) reportMigrationProgress(table.name, cursor);
    }
  }

  for (let cursor = ""; ;) {
    const idempotency = await database.query<{
      idempotency_key: string;
      request_fingerprint: string;
      response_json: unknown;
    }>(
      `SELECT idempotency_key, request_fingerprint, response_json
         FROM blogbot_idempotency
        WHERE idempotency_key > $1
        ORDER BY idempotency_key
        LIMIT $2`,
      [cursor, MIGRATION_PAGE_SIZE]
    );
    if (idempotency.rows.length === 0) break;
    const lastKey = idempotency.rows[idempotency.rows.length - 1]!.idempotency_key;
    await database.transaction(async (transaction) => {
      for (const row of idempotency.rows) {
        if (!reseal || isEncryptedEnvelopeV2(row.response_json)) {
          if (!/^[a-f0-9]{64}$/u.test(row.request_fingerprint)) {
            throw new Error("LOCAL_IDEMPOTENCY_FINGERPRINT_INVALID");
          }
          protector.open(
            row.response_json,
            backendContext(
              "blogbot_idempotency",
              row.idempotency_key,
              "response_json"
            )
          );
          continue;
        }
        // A stored response has no identity field to bind to its key, so the
        // only available statement is that it is still a JSON container.
        const plaintext = protector.openLegacy(
          row.response_json,
          (candidate) => isPlainRecord(candidate) || Array.isArray(candidate)
        );
        const fingerprint = createHash("sha256")
          .update(row.request_fingerprint)
          .digest("hex");
        await transaction.query(
          `UPDATE blogbot_idempotency
              SET request_fingerprint = $2,
                  response_json = $3::jsonb
            WHERE idempotency_key = $1`,
          [
            row.idempotency_key,
            fingerprint,
            JSON.stringify(
              protector.seal(
                plaintext,
                backendContext(
                  "blogbot_idempotency",
                  row.idempotency_key,
                  "response_json"
                )
              )
            )
          ]
        );
      }
      if (reseal) {
        await writeMigrationProgress(
          transaction,
          "backend",
          "blogbot_idempotency",
          lastKey
        );
      }
    });
    cursor = lastKey;
    if (reseal) reportMigrationProgress("blogbot_idempotency", cursor);
  }

  if (reseal) {
    await database.transaction(async (transaction) => {
      await transaction.query(
        `INSERT INTO blogbot_encryption_migrations (scope, version)
         VALUES ('backend', 2)`
      );
      await transaction.query(
        "DELETE FROM blogbot_encryption_migration_progress WHERE scope = 'backend'"
      );
    });
  }
}

function isPlainRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isRecordWithIdentity(
  value: unknown,
  identityField: string,
  key: string
): value is Record<string, unknown> {
  return isPlainRecord(value) && value[identityField] === key;
}

async function readMigrationProgress(
  database: PGliteQueryPort,
  scope: string,
  tableName: string
): Promise<string> {
  const result = await database.query<{ last_key: string }>(
    `SELECT last_key FROM blogbot_encryption_migration_progress
      WHERE scope = $1 AND table_name = $2`,
    [scope, tableName]
  );
  return result.rows[0]?.last_key ?? "";
}

async function writeMigrationProgress(
  client: PGliteQueryPort,
  scope: string,
  tableName: string,
  lastKey: string
): Promise<void> {
  await client.query(
    `INSERT INTO blogbot_encryption_migration_progress (scope, table_name, last_key)
     VALUES ($1, $2, $3)
     ON CONFLICT (scope, table_name) DO UPDATE SET last_key = EXCLUDED.last_key`,
    [scope, tableName, lastKey]
  );
}

/**
 * The desktop cannot tell a migrating engine from a hung one: open() has not
 * resolved, so no request is answered. A page marker on stderr carries only a
 * table name and a row key — never row contents.
 */
function reportMigrationProgress(tableName: string, lastKey: string): void {
  try {
    process.stderr.write(
      `[Blogbot] LOCAL_MIGRATION_PROGRESS ${tableName} ${createHash("sha256").update(lastKey).digest("hex").slice(0, 12)}\n`
    );
  } catch {
    // Progress reporting must never fail a migration page.
  }
}

async function applyLocalMigrations(database: PGlite): Promise<void> {
  await database.exec(MIGRATION_LEDGER_SQL);
  const applied = await database.query<{
    version: number;
    name: string;
    sha256: string;
  }>(
    "SELECT version, name, sha256 FROM blogbot_schema_migrations ORDER BY version"
  );
  const byVersion = new Map(applied.rows.map((migration) => [migration.version, migration]));
  const supportedVersions = new Set<number>(
    LOCAL_MIGRATIONS.map((migration) => migration.version)
  );
  for (const migration of applied.rows) {
    if (!supportedVersions.has(migration.version)) {
      throw new Error(
        `LOCAL_MIGRATION_NEWER_THAN_BINARY: migration ${migration.version} is not supported`
      );
    }
  }

  for (const migration of LOCAL_MIGRATIONS) {
    const sha256 = createHash("sha256").update(migration.sql).digest("hex");
    const existing = byVersion.get(migration.version);
    if (existing) {
      if (existing.name !== migration.name || existing.sha256 !== sha256) {
        throw new Error(
          `LOCAL_MIGRATION_DRIFT: migration ${migration.version} does not match its recorded hash`
        );
      }
      continue;
    }
    await database.transaction(async (transaction) => {
      await transaction.exec(migration.sql);
      await transaction.query(
        `INSERT INTO blogbot_schema_migrations (version, name, sha256)
         VALUES ($1, $2, $3)`,
        [migration.version, migration.name, sha256]
      );
    });
  }
}

async function readSyncSnapshot(
  client: PGliteQueryPort,
  protector: JsonProtector,
  afterCursor: number
): Promise<SyncResult> {
  const automation = await client.query<JsonRow>(
    "SELECT value FROM blogbot_automation WHERE singleton_id = 1"
  );
  const revisions = await client.query<JsonRow>(
    "SELECT id AS key, value FROM blogbot_revisions ORDER BY id"
  );
  const approvals = await client.query<JsonRow>(
    "SELECT revision_id AS key, value FROM blogbot_approvals ORDER BY revision_id"
  );
  const highRiskApprovals = await client.query<JsonRow>(
    `SELECT revision_id AS key, value
       FROM blogbot_high_risk_approvals
      ORDER BY revision_id`
  );
  const outbox = await client.query<JsonRow>(
    "SELECT id AS key, value FROM blogbot_outbox ORDER BY id"
  );
  const jobs = await client.query<JsonRow>(
    "SELECT id AS key, value FROM blogbot_jobs ORDER BY id"
  );
  const changes = await client.query<ChangeRow>(
    `SELECT cursor, kind, entity_id
       FROM blogbot_changes
      WHERE cursor > $1
      ORDER BY cursor`,
    [afterCursor]
  );
  const cursor = await client.query<{ cursor: string | number }>(
    "SELECT COALESCE(MAX(cursor), 0) AS cursor FROM blogbot_changes"
  );

  return {
    serverCursor: Number(cursor.rows[0]?.cursor ?? 0),
    snapshot: {
      automation: protector.open<AutomationSettings>(
        automation.rows[0]?.value,
        backendContext("blogbot_automation", "1")
      ),
      revisions: revisions.rows.map(
        (row) => protector.open<ArticleRevision>(
          row.value,
          backendContext("blogbot_revisions", requiredKey(row))
        )
      ),
      approvals: approvals.rows.map(
        (row) => protector.open<Approval | ApprovalV3>(
          row.value,
          backendContext("blogbot_approvals", requiredKey(row))
        )
      ),
      highRiskApprovals: highRiskApprovals.rows.map(
        (row) => protector.open<HighRiskApproval>(
          row.value,
          backendContext(
            "blogbot_high_risk_approvals",
            requiredKey(row)
          )
        )
      ),
      outbox: outbox.rows.map(
        (row) => protector.open<OutboxEffect>(
          row.value,
          backendContext("blogbot_outbox", requiredKey(row))
        )
      ),
      jobs: jobs.rows.map((row) => protector.open<BackendJob>(
        row.value,
        backendContext("blogbot_jobs", requiredKey(row))
      ))
    },
    changes: changes.rows.map((row) => ({
      cursor: Number(row.cursor),
      kind: row.kind,
      entityId: row.entity_id
    }))
  };
}

async function readRevisionListSnapshot(
  client: PGliteQueryPort,
  protector: JsonProtector
): Promise<RevisionListSnapshot> {
  const [revisions, approvals, highRiskApprovals] = await Promise.all([
    client.query<JsonRow>("SELECT id AS key, value FROM blogbot_revisions ORDER BY id"),
    client.query<JsonRow>("SELECT revision_id AS key, value FROM blogbot_approvals ORDER BY revision_id"),
    client.query<JsonRow>("SELECT revision_id AS key, value FROM blogbot_high_risk_approvals ORDER BY revision_id")
  ]);
  return {
    revisions: revisions.rows.map((row) => protector.open<ArticleRevision>(row.value, backendContext("blogbot_revisions", requiredKey(row)))),
    approvals: approvals.rows.map((row) => protector.open<Approval | ApprovalV3>(row.value, backendContext("blogbot_approvals", requiredKey(row)))),
    highRiskApprovals: highRiskApprovals.rows.map((row) => protector.open<HighRiskApproval>(row.value, backendContext("blogbot_high_risk_approvals", requiredKey(row))))
  };
}

function revisionListSummary(revision: ArticleRevision): ArticleRevision {
  return {
    id: revision.id,
    ...(revision.supersedesRevisionId ? { supersedesRevisionId: revision.supersedesRevisionId } : {}),
    state: revision.state,
    tr: { title: revision.tr.title, slug: revision.tr.slug },
    section: revision.section,
    articleType: revision.articleType,
    ...(revision.riskLevel ? { riskLevel: revision.riskLevel } : {}),
    scheduledAt: revision.scheduledAt,
    // A summary needs claim/source policy state but never source excerpts,
    // translated bodies, generated files, or base64 media payloads.
    sources: revision.sources.map(({ evidenceExcerpt: _excerpt, ...source }) => structuredClone(source)),
    claims: structuredClone(revision.claims)
  } as unknown as ArticleRevision;
}

async function writeRevisionListIndex(
  client: PGliteQueryPort,
  protector: JsonProtector,
  revision: ArticleRevision
): Promise<void> {
  const scheduledAtUnixMs = Date.parse(revision.scheduledAt);
  if (!Number.isFinite(scheduledAtUnixMs)) {
    throw new Error("REVISION_SCHEDULE_INVALID");
  }
  await client.query(
    `INSERT INTO blogbot_revision_list_index
      (revision_id, scheduled_at_unix_ms, supersedes_revision_id, revision_state, value)
     VALUES ($1, $2, $3, $4, $5::jsonb)
     ON CONFLICT (revision_id) DO UPDATE SET
       scheduled_at_unix_ms = EXCLUDED.scheduled_at_unix_ms,
       supersedes_revision_id = EXCLUDED.supersedes_revision_id,
       revision_state = EXCLUDED.revision_state,
       value = EXCLUDED.value`,
    [
      revision.id,
      scheduledAtUnixMs,
      revision.supersedesRevisionId ?? null,
      revision.state,
      JSON.stringify(protector.seal(
        revisionListSummary(revision),
        backendContext("blogbot_revision_list_index", revision.id)
      ))
    ]
  );
}

async function backfillRevisionListIndex(
  database: PGliteDatabasePort,
  protector: JsonProtector
): Promise<void> {
  // Revision rows carry translated bodies, generated files and base64 media, so
  // this loop is paged and committed page by page: reading every missing
  // revision into one transaction is what exhausted the sidecar's heap on a
  // workspace large enough to need the backfill in the first place.
  for (let cursor = ""; ;) {
    const missing = await database.query<JsonRow>(
      `SELECT id AS key, value FROM blogbot_revisions revision
        WHERE revision.id > $1
          AND NOT EXISTS (
            SELECT 1 FROM blogbot_revision_list_index idx WHERE idx.revision_id = revision.id
          )
        ORDER BY revision.id
        LIMIT $2`,
      [cursor, MIGRATION_PAGE_SIZE]
    );
    if (missing.rows.length === 0) break;
    await database.transaction(async (transaction) => {
      for (const row of missing.rows) {
        const id = requiredKey(row);
        const revision = protector.open<ArticleRevision>(
          row.value,
          backendContext("blogbot_revisions", id)
        );
        await writeRevisionListIndex(transaction, protector, revision);
      }
    });
    cursor = requiredKey(missing.rows[missing.rows.length - 1]!);
    reportMigrationProgress("revision-list-index", cursor);
  }
  await backfillRevisionListState(database, protector);
}

/**
 * Fills the plaintext state column an existing index row predates. The state is
 * read from the small list projection rather than the revision itself, so the
 * backfill never opens an article body.
 */
async function backfillRevisionListState(
  database: PGliteDatabasePort,
  protector: JsonProtector
): Promise<void> {
  for (let cursor = ""; ;) {
    const rows = await database.query<{ revision_id: string; value: unknown }>(
      `SELECT revision_id, value FROM blogbot_revision_list_index
        WHERE revision_state IS NULL AND revision_id > $1
        ORDER BY revision_id
        LIMIT $2`,
      [cursor, MIGRATION_PAGE_SIZE]
    );
    if (rows.rows.length === 0) break;
    await database.transaction(async (transaction) => {
      for (const row of rows.rows) {
        // Startup is deliberately not the ciphertext integrity gate — that is
        // verifyEncryptionIntegrity(). A row that will not open keeps a null
        // state, which only means it stays in the due list and is judged by the
        // editorial eligibility check as before.
        let state: string | undefined;
        try {
          state = protector.open<ArticleRevision>(
            row.value,
            backendContext("blogbot_revision_list_index", row.revision_id)
          ).state;
        } catch {
          continue;
        }
        await transaction.query(
          "UPDATE blogbot_revision_list_index SET revision_state = $2 WHERE revision_id = $1",
          [row.revision_id, state]
        );
      }
    });
    cursor = rows.rows[rows.rows.length - 1]!.revision_id;
    reportMigrationProgress("revision-list-state", cursor);
  }
}

async function readRevisionSummarySnapshot(
  client: PGliteQueryPort,
  protector: JsonProtector,
  options: RevisionListReadOptions
): Promise<RevisionListSnapshot> {
  const limit = Math.min(Math.max(1, options.limit ?? 100), 200);
  const rows = await client.query<{ revision_id: string; value: unknown }>(
    `SELECT revision_id, value FROM blogbot_revision_list_index
      ORDER BY scheduled_at_unix_ms DESC, revision_id DESC
      LIMIT $1`,
    [limit]
  );
  const revisions = rows.rows.map((row) => protector.open<ArticleRevision>(
    row.value,
    backendContext("blogbot_revision_list_index", row.revision_id)
  ));
  const revisionIds = revisions.map((revision) => revision.id);
  const [approvalRows, highRiskApprovalRows] = revisionIds.length === 0
    ? [{ rows: [] as JsonRow[] }, { rows: [] as JsonRow[] }]
    : await Promise.all([
      client.query<JsonRow>(
        "SELECT revision_id AS key, value FROM blogbot_approvals WHERE revision_id = ANY($1::text[])",
        [revisionIds]
      ),
      client.query<JsonRow>(
        "SELECT revision_id AS key, value FROM blogbot_high_risk_approvals WHERE revision_id = ANY($1::text[])",
        [revisionIds]
      )
    ]);
  return {
    revisions,
    approvals: approvalRows.rows.map((row) => protector.open<Approval | ApprovalV3>(
      row.value,
      backendContext("blogbot_approvals", requiredKey(row))
    )),
    highRiskApprovals: highRiskApprovalRows.rows.map((row) => protector.open<HighRiskApproval>(
      row.value,
      backendContext("blogbot_high_risk_approvals", requiredKey(row))
    ))
  };
}

async function readDashboardSync(
  client: PGliteQueryPort,
  protector: JsonProtector,
  afterCursor: number,
  options: DashboardReadOptions = {}
): Promise<DashboardSyncResult> {
  const automation = await client.query<JsonRow>(
    "SELECT value FROM blogbot_automation WHERE singleton_id = 1"
  );
  // The bounded window must be the newest rows, and neither primary key is
  // chronological: an outbox id is a random UUID and a job id is an opaque
  // client identifier, so ordering on it returned a uniformly random subset.
  // `seq` is the insertion-order identity column; every timestamp lives inside
  // the sealed value and cannot be ordered on without decrypting everything.
  const outbox = options.outboxLimit === undefined
    ? await client.query<JsonRow>("SELECT id AS key, value FROM blogbot_outbox ORDER BY id")
    : await client.query<JsonRow>(
      "SELECT key, value FROM (SELECT id AS key, value, seq FROM blogbot_outbox ORDER BY seq DESC LIMIT $1) recent ORDER BY seq",
      [options.outboxLimit]
    );
  const jobs = options.jobLimit === undefined
    ? await client.query<JsonRow>("SELECT id AS key, value FROM blogbot_jobs ORDER BY id")
    : await client.query<JsonRow>(
      "SELECT key, value FROM (SELECT id AS key, value, seq FROM blogbot_jobs ORDER BY seq DESC LIMIT $1) recent ORDER BY seq",
      [options.jobLimit]
    );
  const changes = options.changeLimit === undefined
    ? await client.query<ChangeRow>(
      "SELECT cursor, kind, entity_id FROM blogbot_changes WHERE cursor > $1 ORDER BY cursor",
      [afterCursor]
    )
    : await client.query<ChangeRow>(
      `SELECT cursor, kind, entity_id
         FROM blogbot_changes
        WHERE cursor > $1
        ORDER BY cursor
        LIMIT $2`,
      [afterCursor, options.changeLimit]
    );
  const mappedChanges = changes.rows.map((row) => ({
    cursor: Number(row.cursor),
    kind: row.kind,
    entityId: row.entity_id
  }));
  return {
    serverCursor: mappedChanges.at(-1)?.cursor ?? afterCursor,
    automation: protector.open<AutomationSettings>(
      automation.rows[0]?.value,
      backendContext("blogbot_automation", "1")
    ),
    outbox: outbox.rows.map((row) => protector.open<OutboxEffect>(
      row.value,
      backendContext("blogbot_outbox", requiredKey(row))
    )),
    jobs: jobs.rows.map((row) => protector.open<BackendJob>(
      row.value,
      backendContext("blogbot_jobs", requiredKey(row))
    )),
    changes: mappedChanges
  };
}

function backendContext(table: string, key: string, field = "value") {
  return { table, key, field };
}

function requiredKey(row: JsonRow): string {
  if (!row.key) {
    throw new Error("LOCAL_DATA_IDENTITY_MISSING");
  }
  return row.key;
}

function isUniqueViolation(error: unknown): boolean {
  return (
    typeof error === "object" &&
    error !== null &&
    "code" in error &&
    (error as { code?: unknown }).code === "23505"
  );
}
